### ISSUE TITLE
RoleMapping not work well with mongoDB connector

### ISSUE THREAD

**Issue by kimkha** [strongloop/loopback-connector-mongodb#363] opened 2017-03-27 10:03 UTC
I check with [this example](https://github.com/strongloop/loopback-example-access-control/blob/master/server/boot/sample-models.js)

After insert new record, I open mongoDB, and found that RoleMapping.principalId is `String` type (not `ObjectID`). The point is, when make the query, `buildWhere` function will convert that string to ObjectID. Then there is no result after that.

I think the problem is:

* The `MongoDB.create` function didn't convert String to ObjectID
* The `MongoDB.buildWhere` function always convert String to ObjectID.

So the type in MongoDB is mismatch.

Please fix.

**Comment by jonilappalainen** [comment] 2017-04-14 18:36
Noticed the same problem. Role.isInRole doesn't find the RoleMapping because of this. Need fix.

**Comment by b-admike** [comment] 2017-04-20 14:09
@kimkha thank you for your description and doing some research on the cause. I have confirmed this is a bug as well on my end.

**Comment by kimkha** [comment] 2017-04-21 02:47
I also fixed on my private repo, can I make a PR for this? I'm not sure, my code may be messy.

**Comment by b-admike** [comment] 2017-04-21 13:48
@kimkha thanks, that would be great. Please review https://github.com/strongloop/loopback-connector-mongodb/blob/master/CONTRIBUTING.md and once you have a PR, I will review and help you land it.

**Comment by kimkha** [comment] 2017-04-21 16:05
DONE, please review

**Comment by b-admike** [comment] 2017-04-21 20:09
@kimkha I have verified your fix in #370 with my version of `loopback-example-access-control`. Once you have added unit tests for your PR, we should be able to close this issue. @jonilappalainen You can also try to see if the issue is fixed for you. You can follow the following steps before running your app if the PR is not merged yet:
```
git clone git@github.com:kimkha/loopback-connector-mongodb.git kimkha-mongodb
cd kimkha-mongodb
npm link
cd /path/to/your/app
npm link loopback-connector-mongodb
```

**Comment by b-admike** [comment] 2017-04-26 15:02
@kimkha @jonilappalainen can you please verify if this issue is fixed if you set `RoleMapping.settings.strictObjectIDCoercion = true` in the `sample-models.js` boot script file while using the same version of the `loopback-connector-mongodb` you used to find the issue?

**Comment by jonilappalainen** [comment] 2017-04-26 19:03
👍  @b-admike it seems to work at least for me with that set in sample-models.js boot script. Cheers!

**Comment by b-admike** [comment] 2017-04-27 18:01
I am going to close this issue because of https://github.com/strongloop/loopback-connector-mongodb/issues/363#issuecomment-297437024, but leave #370 open for further discussion. If anyone objects, we can re-open it again and investigate further.

**Closed** 2017-04-27 18:02 UTC
Labels: apex, bug, review

**Comment by b-admike** [comment] 2017-05-03 14:40
I am going to close this issue because of https://github.com/strongloop/loopback-connector-mongodb/issues/363#issuecomment-297437024. If anyone objects, we can re-open it again and investigate further.

**Comment by kuongknight** [comment] 2018-02-07 07:14
although I set strictObjectIdCoercionFlag for RoleMapping, I still found this issue:

> "loopback": "^3.18.1",
> "loopback-boot": "^2.6.5",
> "loopback-connector-mongodb": "^3.4.1",
> "loopback-connector-redis": "^0.1.0",
> "loopback-datasource-juggler": "^3.15.0"
