### ISSUE TITLE
Why converting string to ObjectId in 'inq' filter?

### ISSUE THREAD

**Issue by coodoo** [strongloop/loopback-connector-mongodb#52] opened 2014-09-11 09:12 UTC
I get the idea behind doing so is to allow querying by _id, but the problem it's causing is any string of length 12 or 24 will be converted too, even worser if those strings matches ObjectID format, they will be converted to ObjectID type when they should remain String type.

In short, this kind of "forced" conversion is kind of a surprise and smell like a hack?

``` js
} else if (spec === 'inq') {
        query[k] = { $in: cond.map(function (x) {
          if ('string' !== typeof x) return x;
          return ObjectID(x);
        })};
      } 
```

See full code here:
http://goo.gl/Xwhlj4

**Comment by raymondfeng** [comment] 2015-02-08 19:10
@SSchaaf Can you submit your fix as a patch?

**Comment by terrence0488** [comment] 2015-05-02 11:03
@raymondfeng hi Raymond, is this going to be fixed? Right now, if I would like to do a inq search to a non id field, how can i do it? Im trying to avoid changing code in the mongo-connector.

**Comment by wrensburg** [comment] 2015-06-05 05:32
:+1: Having to hack the framework to achieve this!

**Comment by chrisamoore** [comment] 2015-06-05 15:55
:+1: Def need this. /cc @ShubhraKar @dashby3000

**Comment by ekussberg** [comment] 2015-08-25 12:52
@raymondfeng @bajtos is this problem patched/fixed? We had several times already this issue and needed to change the type of ID to string from ObjectId as INQ just converts the String always to ObjectId and MongoDB return zero results. Could you provide a fix or solution how to make INQ with simple strings? I tried already this
```
"deliveryTourId": {
      "type": "ObjectId",
}
```
It also doesnt work. If i put string, then it returns 0 as string != objectId.

**Comment by raymondfeng** [comment] 2015-08-25 22:22
Can you try with https://github.com/strongloop/loopback-connector-mongodb/pull/174?

**Comment by totalard** [comment] 2017-02-05 03:33
Not fixed Yet

**Comment by shallker** [comment] 2017-04-10 01:33
Still not fixed!!!!

**Comment by shallker** [comment] 2017-04-10 01:36
if the string length is 24, it will be always treated as ObjectId automatically, what is the purpose of this design?

**Comment by bajtos** [comment] 2017-04-11 12:51
I am reopening the issue then. @strongloop/sq-lb-apex could you PTAL?

**Comment by vinzentt** [comment] 2017-04-26 14:08
This bug also breaks RoleMapping built-in model requests. 
It has a string field called principalId, so if you try to find the roles for a user, you cannot, you have to access MongoDb native connector via `MyModel.getDataSource().connector.collection(MyModel.modelName)`.

**Comment by anjanarana** [comment] 2017-04-27 06:47
Hi Guys,

You can convert your string to Object using

var ObjectID = require('mongodb').ObjectID;

Pass the String parameter inside parenthesis like mentioned below.

ObjectID(stringvalue)

**Comment by jpradeep2003** [comment] 2017-05-02 17:17
Can someone please share a workaround for this situation?
I have 2 models viz. Parent and Child. Child has a foreign-key (name "parentId", type "string"). Using find on Child with where filter for parentId always returns empty results array. After hours of trying to root-cause and solve that problem, I finally landed here. Since this issue is unresolved for such a long time, I hope there is a workaround that is probably being used by most people for this very common use-case.

**Comment by lovingyugs** [comment] 2017-05-08 19:13
Using loopback model-
Earlier I was having this properties and relations in my purchase.json file
####
       "properties": {
           "user_id": {
           "type": "string",
           "required": true
        },
        "vendor_id": {
           "type": "string",
           "required": true
         }
    },
        "relations": {
           "purchase":` {
           "type": "belongsTo",
           "model": "user",
           "foreignKey": "user_id"
       }
      },

So, It was storing userId as objectId and vendorId as string in my purchase collection of MongoDB.

Now I have 
####
       "properties": {
           "user_id": {
              "type": "string",
               "required": true
            },
          "vendor_id": {
             "type": "string",
             "required": true
            }
         },
        "relations": {
           "purchase": {
           "type": "belongsTo",
           "model": "user",
           "foreignKey": "user_id"
      }, 
       "purchase": {
          "type": "belongsTo",
          "model": "vendors",
          "foreignKey": "vendor_id"
         }
      },

Now both userId and VendorId is stored as ObjectId in my purchase collection.  
Adding "belongsTo" relation of purchase with vendors collection worked for me. No need to convert the string id to MongoDB objectId and then do things.

**Comment by droig** [comment] 2017-06-01 03:18
I had the same problem and ended up concatenating a char to the field in order to make it work Haven't tried with relations though.

**Comment by ssh24** [comment] 2017-06-18 15:50
To avoid id of type string being always converted to ObjectID when the string length is 24 and has the format the of an ObjectID i.e `/^[0-9a-fA-F]{24}$/`, you can use the **strictObjectIDCoercion** flag and set it to true in the model-definiton.

Here is an example code snippet:

**model-definition.js**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true,
    "strictObjectIDCoercion": true
  },
  "properties": {
    "id": {
      "type": "string",
      "required": true,
      "id": true
    },
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var Employee = app.models.Employee;

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('Automigrate complete');

    Employee.create([{
      id: '59460487e9532ae90c324b59',
      name: 'Bob',
    }, {
      id: '59460487e9532ae90c324b5a',
      name: 'Sam',
    }, {
      id: '420',
      name: 'Foo',
      age: 1,
    }, {
      id: '21',
      name: 'Bar',
    }], function(err, result) {
      if (err) throw err;
      console.log('\nCreated employees: ' + util.inspect(result, 4));

      Employee.find({where: {id: {inq: ['59460487e9532ae90c324b59',
        '59460487e9532ae90c324b5a']}}},
      function(err, result) {
        if (err) throw err;
        console.log('\nFound instance with inq: ' + util.inspect(result, 4));
      });
    });
  });
};
```

**output**
```bash
sakibs-mac:mongodb-52 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Automigrate complete

Created employees: [ { id: '59460487e9532ae90c324b59', name: 'Bob' },
  { id: '59460487e9532ae90c324b5a', name: 'Sam' },
  { id: '420', name: 'Foo', age: 1 },
  { id: '21', name: 'Bar' } ]

Found instance with inq: [ { name: 'Bob', id: '59460487e9532ae90c324b59' },
  { name: 'Sam', id: '59460487e9532ae90c324b5a' }
```

**test with mongodb version:** loopback-connector-mongodb@3.1.0

Hope this solves this issue. Please let me know if there any questions/concerns.

**Closed** 2017-06-22 16:26 UTC
Labels: apex, bug, triaging

**Comment by benawarez** [comment] 2017-07-04 07:24
I have v1.17.0 and my inq filter for an array of ID's doesn't work.  I've been troubleshooting this for days and I'm stuck.  I've tried v1.18.0 all the way to v3.2.0, updated my mongodb and loopback-connector modules to the latest, running mongodb database 3.0.8 to the latest 3.4... all combinations that you can think of... I can't figure it out.  From reading all the posts, it looks like the fix got applied on v1.18.0 but documented on v3.2.0?  

Whenever I run anything higher than v1.17.0 with strictObjectIDCoercion = true, my authentication fails altogether.

The documentation of the fix is posted in Looback 3.0.  I'm running 2.37.0... could that be the problem?  

Please advise the combination of modules I need to get the strictObjectIDCoercion to work. 

Thanks in advance.

**Comment by ssh24** [comment] 2017-07-04 15:40
@benawarez My reproduction above was with:
```
loopback@3.8.0
loopback-datasource-juggler@3.9.1
loopback-connector-mongodb@3.1.0
```

**Comment by benawarez** [comment] 2017-07-04 19:59
I upgraded my loopback from 2.37.0 to v3.8.0 and your recommended juggler and mongodb connector versions.  However, in doing so, my passportconfigurator.setupModels is now failing to load preventing the app from starting.  I upgraded the loopback-component-passport to the latest just now (v3.4.0) and still having the same issue.

I've tried your versions with module mongodb@2.2.20 and @2.2.29.

Any other dependencies I need to verify to make this work (i.e. mongodb database version, loopback-connector, etc)?

Is it possible to get this to work on LB2.x with loopback-connector-mongodb@1.17.0 or 1.18.0 as this thread suggests?

https://github.com/strongloop/loopback-connector-mongodb/issues/302

Thanks in advance.


Below is the error:


assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: The model type must be a constructor or model name
    at Registry.getModelByType (\node_modules\loopback\lib\registry.js:331:3)
    at Function.loopback.getModelByType (\node_modules\loopback\lib\loopback.js:325:39)
    at PassportConfigurator.setupModels (\node_modules\loopback-component-passport\lib\passport-configurator.js:42:50)

**Comment by ssh24** [comment] 2017-07-05 00:32
@benawarez I think the error you are facing is due to the [loopback-component-passport](https://github.com/strongloop/loopback-component-passport). I do not have your app so I cannot reproduce this it to the same extent.

I have done the exact reproduction in https://github.com/strongloop/loopback-connector-mongodb/issues/52#issuecomment-309285598 with the following versions and it worked:
```json
{
  "name": "mongodb-strictObjectIDCoercion-app",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "lint": "eslint .",
    "start": "node .",
    "posttest": "npm run lint && nsp check"
  },
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^1.17.0",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },
  "devDependencies": {
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "mongodb-strictObjectIDCoercion-app"
}
``` 

Do you mind creating a ticket for your issue in [loopback component passport issues](https://github.com/strongloop/loopback-component-passport/issues) with detailed reproduction steps or even better, with a link to your app sandbox?

**Comment by benawarez** [comment] 2017-07-05 01:43
I tried your versions (but the loopback-boot) and my app would not change view after successfully authenticating.

The strange thing is, all my queries with the inq to an array of IDs was working once upon a time until I'm not exactly sure what changed.  My version history doesn't help because it only tracks my code changes and not the modules that gets added, removed, and updated.

I've already began querying MongoDB directly for inq IDs related tasks as a work around... so far so good.  When I get done, I'll look into the loopback component passport.  Thanks for the swift response.
