### ISSUE TITLE
NumberDecimal data type issue with elements of an array defined under an object schema

### ISSUE THREAD

**Issue by SandeepVanama** [strongloop/loopback-connector-mongodb#492] opened 2019-01-30 21:53 UTC
I am using model JSON file to load a document in Mongo DB using loopback mechanism. I see the NumberDecimal is working fine only for the elements defined inside an array object present at root level but not for the elements defined inside an Array of a Object schema. 

Please find below obeservations,

1. It is NOT working for the the field "testDecimal" defined at Root.imdb.innerArray.Item[index].testDecimal <The innerArray array is present inside an object schema named imdb)
2. It appears to be working fine for the fields defined at Root.tickets.Item[index].unitprice <The tickets array is present at root level)
3. It appears to be working fine for the fields defined at nested object level, Root.imdb.innerObj.innerObj.innerObj.innerObj.testDecimal

Attached model JSON file (movies.json) & the output file(movies_sample.json) for reference. 
I am using the loopback-connector-mongodb@3.9.2 version.

Please check and do the needful to resolve the issue stated at point # 1. Let me know for any more details needed.

**Comment by SandeepVanama** [comment] 2019-01-30 22:02
Couldn't attach the files with .JSON extension, so attaching them as .txt. 

[movies.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2814642/movies.txt)
[movies_sample.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2814643/movies_sample.txt)

Thank you in advance for the support.!!

**Comment by dhmlau** [comment] 2019-01-31 16:41
Closing as duplicate of https://github.com/strongloop/loopback-connector-mongodb/issues/493

**Closed by dhmlau** 2019-01-31 16:41 UTC
