### ISSUE TITLE
Failed to connect to server on first connect - No retry

### ISSUE THREAD

**Issue by rudijs** [strongloop/loopback-connector-mongodb#268] opened 2016-07-28 06:08 UTC
Hi,

I'm seeing some inconsistent reconnect behavior that I can't resolve so would like to ask for some assistance please.

Using Mongo 3.2.6 and these loopback\* versions:

```
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^1.13.3",
    "loopback-datasource-juggler": "^2.39.0",
    "loopback-phase": "^1.3.0",
```

```
 grep version node_modules/mongodb/package.json
  "version": "2.2.4"
```

MongoDB configuration is:

```
{
  "mongodb": {
    "host": "192.168.33.100",
    "port": 27017,
    "database": "api-ep",
    "name": "mongodb",
    "connector": "mongodb",
    "server": {
      "auto_reconnect": true,
      "autoReconnect": true,
      "reconnectTries": 2000,
      "reconnectInterval": 1000
    }
  }
}
```

You can see I'm trying two different forms of the auto reconnect property name.

I've also tried using one form or the other only.

**Scenario 1 Application startup**)

If MongoDB is offline..

then I start the loopback app this error is reported:

```
Connection fails:  { MongoError: failed to connect to server [192.168.33.100:27017] on first connect
    at .<anonymous> (/Users/rudi/projects/apifactory/node_modules/mongodb-core/lib/topologies/server.js:295:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/rudi/projects/apifactory/node_modules/mongodb-core/lib/connection/pool.js:251:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/rudi/projects/apifactory/node_modules/mongodb-core/lib/connection/connection.js:150:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at process.fallback (/Users/rudi/projects/apifactory/node_modules/async-listener/index.js:482:15)
  name: 'MongoError',
  message: 'failed to connect to server [192.168.33.100:27017] on first connect' } 
It will be retried for the next request.
```

When I make requests that use MongoDB they timeout after 5 seconds.

When MongoDB is restarted the requests continue to timeout after 5 seconds.

```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Timeout in connecting after 5000 ms",
    "stack": "Error: Timeout in connecting after 5000 ms\n    at Timeout.<anonymous> (/Users/rudi/projects/apifactory/node_modules/loopback-datasource-juggler/lib/datasource.js:2131:10)\n    at Timeout._onTimeout (/Users/rudi/projects/apifactory/node_modules/async-listener/glue.js:188:31)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)"
  }
}
```

There's no reconnect.

**Scenario 2 - MongoDB stop start**)

When loopback is running..

Then MongoDB stops, requests that need a mongodb connection do not timeout after 5 seconds they are just very long running and eventually reply with:

```
{
  "error": "no response from server"
}
```

When MongoDB restarts, reconnect is OK and immediate and request works as expected.

**Summary**)

I think there's two issues here:
1. Not reconnecting if MongoDB is offline before the loopback app starts
2. When MongoDB goes offline when the loopback app is online, requests don't timeout after 5 seconds.

Ideally I'd like to have auto reconnect work consistent and prompt timeouts when the database is offline.

It's not good if the web app won't start if the db is offline.

Can you see where I'm going wrong or mis-configured?

Any advice or direction very much appreciated.

Thanks!

**Comment by MylesHarding** [comment] 2016-08-16 09:45
I am seeing the same issue.

**Comment by lushibi** [comment] 2016-09-14 04:02
same problem, especially when debugging with node-debug, any resolution?

**Comment by jannyHou** [comment] 2016-10-11 17:46
@rudijs I am trying to reproduce your problem.

- For scenario 2, I reproduced your problem and label it as a bug.
  But as a workaround, my app returns error 500 when "lb app running but mongo server shut down" if I don't provide the `server` configs for mongodb. 
  MongoDB shell version: 3.2.6
  My dependencies version
  ```
   "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-cloudant": "^1.0.11",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.39.0",
   ```

- And for scenario 1, the app **won't** run if your mongodb server is down right?

**Comment by rudijs** [comment] 2016-10-12 01:24
@jannyHou Hi, yes for scenario 1 the app won't run at all if MongoDB is down.

So it's quite serious.

We expect the app (express server) to start and just return a valid error, rather than not start at all.

**Comment by rudijs** [comment] 2016-10-12 01:25
@jannyHou Will try scenario 2 without the server properties shortly and reply here with the results.

**Comment by rudijs** [comment] 2016-10-12 03:57
@jannyHou For scenario 2 seeing the same behavior as described with or without the server reconnection properties.

**Comment by jannyHou** [comment] 2016-10-12 15:04
@rudijs If you want to run the app no matter ds server is open or down, we have a config variable to do it, in `datasources.json`, set `lazyConnect` to true:

```json
"mongoDS": {
  "lazyConnect": true
}
```

Please check doc http://loopback.io/doc/en/lb2/datasources.json.html#standard-properties for details

**Comment by rudijs** [comment] 2016-10-13 01:47
@jannyHou I've just tried using the "lazyConnect" option as detailed at:

http://loopback.io/doc/en/lb2/datasources.json.html#standard-properties

I'm still having problems though.

The server does start up ok, lazy, but when I turn MongoDB on (was off on nodejs start up) there's no reconnect.

The server remains unable to connect to MongoDB. Seems similar to scenario 1 above - no reconnect.

**Comment by jannyHou** [comment] 2016-10-13 14:41
@rudijs I also noticed the bug after I wrote that comment, I created a bug issue for it:
https://github.com/strongloop/loopback/issues/2850

Sorry I thought you didn't see that comment and since it won't solve the problem I deleted it.

**Comment by yellowred** [comment] 2016-11-04 02:06
+1 same issue just bit me in production, had to restart the app in order to reconnect, because auto reconnect did not work.

if any details or help I can provide please let me know.

**Comment by Alex2357** [comment] 2016-11-05 19:53
I experience same problem very often.  I'm using Nodejs and old 2.4.8 mongodb.
Here's some info

Sun Nov 06 06:46:13.968 [initandlisten] db version v2.4.8
Sun Nov 06 06:46:13.968 [initandlisten] git version: a350fc38922fbda2cec8d5dd842237b904eafc14
Sun Nov 06 06:46:13.968 [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1') BOOST_LIB_VERSION=1_49

I'm running Mongo instance on my laptop. When the app started on laptop it works great. No issues found. When I start app on desktop I have errors. My laptop connected to home network via wifi. So desktop connects to laptop using wifi.

**Comment by jannyHou** [comment] 2016-11-07 15:23
Anyone also run into the problem please thumb up on the first comment https://github.com/strongloop/loopback-connector-mongodb/issues/268#issue-168020014

We have a git bug voting system which counts thumbups and accordingly decide the priority.

**Comment by superkhau** [comment] 2016-11-08 04:09
>We have a git bug voting system which counts # of thumbups and accordingly decide the priority.

We do not have this system yet, but will have one in place once we flush out the details. See https://github.com/strongloop/loopback/issues/2905

**Comment by jannyHou** [comment] 2016-11-08 15:37
@superkhau hmm... isn't https://www.bountysource.com/teams/strongloop/issues tracking the vote?

**Comment by superkhau** [comment] 2016-11-10 07:17
@jannyHou That is true to an extent, but we need to let user's know that is the official system being used, ie. how do they know if we don't document that is the case somewhere?

**Comment by demsey2** [comment] 2016-11-11 03:28
I have the same problem with version 1.17.0 running on AWS EC2 with ELB
1.15.1 works fine

**Comment by viki53** [comment] 2017-01-10 16:36
Hi, same issue here. This is pretty critical as we use LoopBack as a data manager that needs to be connected to a Mongo DB all the time, or at least crash when the DB disconnects.

* If first try fails, LB crashes : a little abrupt, considering it should probably retry if `autoReconnect = true`
* If DB goes down while LB is running, nothing happens at first (no log) until `reconnectInterval * reconnectTries` is done, then I get an error log but the LB process still lives

**Comment by raymondfeng** [comment] 2017-01-10 18:58
@jannyHou See http://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/

**Comment by phairow** [comment] 2017-03-09 17:13
I created this PR since the mongo code was throwing error that prevent the server startup. Maybe there is a better solution than lazyConnect but this worked for me. I had to set lazyConnect: true for this to work.

````
    "accountds": {
        "name": "accountds",
        "connector": "mongodb",
        "url": "mongodb://localhost:27017/accountdb",
        "lazyConnect": true
    }
````

**Comment by phairow** [comment] 2017-03-09 17:14
also, see the PR I created to allow the re-connect above #356

**Comment by dhmlau** [comment] 2017-04-12 20:15
Looks like PR #360 (replacement of #356) has been merged.

**Comment by ssh24** [comment] 2017-06-28 19:18
With respect to the original post in this issue:

**Scenario 1**: _start app when mongodb server is offline_

This will always give the error below, unless the `lazyConnect` flag is specified.
```
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at null.<anonymous> (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```
The `lazyConnect` flag defers the connection to start the application and tries establishing the connection once an endpoint is hit. If at that time, the mongodb server is still down, the connector will try reconnecting with the [default settings](http://mongodb.github.io/node-mongodb-native/core/driver/reference/connecting/connection-settings/), see `autoReconnect`, `reconnectTries` and `reconnectInterval`.

**Scenario 2**: _stop/start mongodb server when the app is running_
As an end user, you can specify [special configs](http://mongodb.github.io/node-mongodb-native/core/driver/reference/connecting/connection-settings/) in the `datasource.json` file to allow reconnection to the mongodb server:
```json
{
  "autoReconnect": true,
  "reconnectTries": 50,
  "reconnectInterval": 1000
}
```
The above will try reconnecting to the mongodb server every second for 50 times. After the timeout is over it throws the expected error without terminating the application:
```
Unhandled error for request GET /api/Employees: Error: MongoDB connection is not established
    at MongoDB.collection (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/loopback-connector-mongodb/lib/mongodb.js:203:11)
    at doExecute (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/loopback-connector-mongodb/lib/mongodb.js:317:29)
    at /Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/loopback-connector-mongodb/lib/mongodb.js:302:7
    at /Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/loopback-connector-mongodb/lib/mongodb.js:170:19
    at connectCallback (/Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/mongodb/lib/mongo_client.js:505:5)
    at /Users/ssh/workspace/sandbox/loopback-sandbox/apps/mongodb/mongodb-268/node_modules/mongodb/lib/mongo_client.js:412:11
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
After restarting the mongodb server, you can hit the application endpoints again without restarting the whole application.

Reproduced with:  `loopback-connector-mongodb@3.1.0`

**Closed** 2017-06-29 15:34 UTC
Labels: apex, backlog, bug, major

**Comment by prashantnirgun** [comment] 2018-01-31 04:06
Has anybody got the solution on which specific npm module version it works please reply urgent

**Comment by Alex2357** [comment] 2018-01-31 21:22
I have had exactly same problem. I resolved it few days later after I posted previously. I was incorrectly using connections. In my case the pool connections was created each time. When I fixed my code I have never experienced this problem. Just put a break point in the library when the pool is created and check if you have multiple stops at that line. If it is you need to fix your code to make it once or not every request to a database. Hope this helps.

**Comment by prashantnirgun** [comment] 2018-02-04 14:45
Alex I am very new to loopback I tried by upgrading all packages to latest now Its showing following error 
  at Pool.<anonymous> (node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/topologies/server.js:336:35)

Alex what changes you made for pool can you share with us

**Comment by raymondfeng** [comment] 2018-05-22 17:54
Please try loopback-datasource-juggler@3.21.0.

You can configure the datasource with `lazyConnect: true`.

**Comment by pookdeveloper** [comment] 2020-01-06 10:28
I have the same error with mysql:
my dependecies in package.json
````
{...
  "dependencies": {
    "@types/node": "^13.1.2",
    "compression": "^1.0.3",
    "connect-multiparty": "^2.2.0",
    "cors": "^2.5.2",
    "fetch": "^1.1.0",
    "file-type": "^12.4.2",
    "helmet": "^3.10.0",
    "json-merger": "^1.1.2",
    "jsonschema": "^1.2.5",
    "jsreport-client": "^1.0.2",
    "loopback": "^3.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.2.0",
    "loopback-component-storage": "^3.6.3",
    "loopback-connector-mysql": "^5.4.2",
    "moment": "^2.24.0",
    "multer": "^1.4.2",
    "mysql": "^2.17.1",
    "puppeteer": "^2.0.0",
    "read-chunk": "^3.2.0",
    "reflect-metadata": "^0.1.13",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^3.0.0",
    "ts-node": "^7.0.0",
    "typeorm": "^0.2.22",
    "typescript": "^3.7.4"
  }
...}

````
