### ISSUE TITLE
1.13.3 does not work with custom Role and User models

### ISSUE THREAD

**Issue by MichaelKohler** [strongloop/loopback-connector-mongodb#243] opened 2016-04-29 15:13 UTC
Hi everyone

We're using custom Role and User models and we discovered that this does not work anymore with version 1.13.3. ```http://localhost:3000/api/users?filter={%22include%22%3A%22roles%22}``` does only return empty arrays for the roles. **With version 1.13.2 this is not a problem at all.**

We have two models (NcUser, NcRole) which are connected through the "roles" relationship (https://github.com/MichaelKohler/loopback-sandbox/blob/roles_1.13.3_mongodb_connector/server/models/nc-user.json, https://github.com/MichaelKohler/loopback-sandbox/blob/roles_1.13.3_mongodb_connector/server/models/nc-role.json). Have a look at the full sandbox-example if you need more information: https://github.com/MichaelKohler/loopback-sandbox/tree/roles_1.13.3_mongodb_connector

Feel free to get back to me if you have any questions, glad to help!

Thanks,
Michael

**Comment by MichaelKohler** [comment] 2016-04-29 17:12
Compare between releases: https://github.com/strongloop/loopback-connector-mongodb/compare/v1.13.2...v1.13.3

Though the principalId is still stored in the MongoDB as string (in the RoleMapping collection), not ObjectId for all current modules, it's converting to an ObjectId (and therefore probably doesn't find it): 

```
{ "_id" : ObjectId("57237539506dde491064ebbf"), "principalType" : "USER", "principalId" : "57237539506dde491064ebbb", "roleId" : ObjectId("57237539506dde491064ebbe") }
```

coming from https://github.com/strongloop/loopback-connector-mongodb/compare/v1.13.2...v1.13.3#diff-567d120f151f51afa9605ebcf0f20106R245

This is the commit that breaks it: https://github.com/strongloop/loopback-connector-mongodb/commit/4ad6ba030f21832f2de74262178d3dcbecc4a926

**Comment by MichaelKohler** [comment] 2016-04-29 17:12
@ raymondfeng do you have any input for me for that case?

**Comment by Amir-61** [comment] 2016-06-23 20:09
Hey @markm186 

This is a duplicate of this issue: https://github.com/strongloop/loopback-connector-mongodb/issues/208

I'm closing this in favour of #208 

Thanks!

**Closed** 2016-06-23 20:09 UTC
Labels: duplicate, triage
