### ISSUE TITLE
Option is not supported in version v.1.18.0

### ISSUE THREAD

**Issue by iliraga** [strongloop/loopback-connector-mongodb#346] opened 2017-02-13 14:00 UTC
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When using the version 1.18.0 of the connector, I get on developer & production environement an error which states that the configuration of the datasource is not valid. In version v.1.17.0 everything works fine. Looks like the connector passes wrong data to the mongodb native client.

### Link to sample repo to reproduce issue (if bug)

Configuration:

```
"mongodb": {
    "host": "localhost",
    "port": 27017,
    "database": "my_database_name",
    "password": "",
    "name": "mongodb",
    "user": "",
    "connector": "loopback-connector-mongodb"
  }


```

### Actual result (if bug)

Getting this error while starting up:

```
Connection fails: MongoError: option host is not supported
It will be retried for the next request.

/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback/lib/application.js:246
    throw err;
    ^
MongoError: option host is not supported
    at validOptions (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/mongodb/lib/mongo_client.js:50:14)
    at Function.MongoClient.connect (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/mongodb/lib/mongo_client.js:194:13)
    at MongoDB.connect (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-connector-mongodb/lib/mongodb.js:138:25)
    at Object.initializeDataSource [as initialize] (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-connector-mongodb/lib/mongodb.js:81:28)
    at DataSource.setup (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-datasource-juggler/lib/datasource.js:343:19)
    at new DataSource (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-datasource-juggler/lib/datasource.js:121:8)
    at Registry.createDataSource (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback/lib/registry.js:355:12)
    at dataSourcesFromConfig (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback/lib/application.js:440:19)
    at Function.app.dataSource (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback/lib/application.js:235:14)
    at /Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/lib/executor.js:190:9
    at /Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/lib/executor.js:281:5
    at Array.forEach (native)
    at forEachKeyedObject (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/lib/executor.js:280:20)
    at setupDataSources (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/lib/executor.js:180:3)
    at execute (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/lib/executor.js:38:3)
    at bootLoopBackApp (/Users/iliraga-hitouch/Documents/projects/dreet.cloud/node_modules/loopback-boot/index.js:154:3)

```

### Additional information (Node.js version, LoopBack version, etc)

Node-Version is v.7.3.0, loopback-version is 2.38.0

**Comment by jannyHou** [comment] 2017-02-13 16:51
@iliraga Thank you for raising up the bug, we will take a look ASAP, it fails all test case and affects lots of users.

**Comment by jannyHou** [comment] 2017-02-13 17:01
same issue as https://github.com/strongloop/loopback-connector-mongodb/issues/344. 
Let's keep discussion there, the bug is caused by `mongodb`'s upgrading to 2.2.23

Close this one as a duplication.

**Closed by jannyHou** 2017-02-13 17:01 UTC
Labels: bug, major, team-apex
