### ISSUE TITLE
[Breaking] 1.13.1 buildWhere no longer turns ID's into ObjectID's

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-mongodb#207] opened 2015-12-15 23:09 UTC
A breaking change is introduced into 0.13.1

The buildWhere function no longer creates objectId from data id. 

The line that is removed is here https://github.com/strongloop/loopback-connector-mongodb/commit/35c4299d9fbc4922e361eba19dfa3b77116b3dc1#diff-567d120f151f51afa9605ebcf0f20106L549

This fundamentally changes the behavior of this function and effects all queries where the id is used.

**Comment by raymondfeng** [comment] 2015-12-15 23:48
Duplicate of #208

**Closed by raymondfeng** 2015-12-15 23:48 UTC
