### ISSUE TITLE
Filter documents where 'type' field doesn't exists not working

### ISSUE THREAD

**Issue by noamtz** [strongloop/loopback-connector-mongodb#218] opened 2015-12-31 17:26 UTC
I have a model called "Form" with fields: "name", "status".  

recently I've added new field called "type".
I need to get old forms that  "type" field doesn't exists so i pass this filter:
```
{
  "where": {
    {"type": {"exists": false}}
  }
}
```
and i'm getting an empty array. (with every other field it works just fine)

I set DEBUG variable to be: 
```
DEBUG=loopback:connector:mongodb
```

and the debug print this lines:
```
  loopback:connector:mongodb all +1ms Form { where: { type: '[object Object]' } }
  loopback:connector:mongodb MongoDB: model=Form command=find +0ms [ { type: '[object Object]' }, [Function] ]
```

and if i try to check existence of different field such as name i get:
```
{
  "where": {
    {"status": {"exists": false}}
  }
}
```
```
  loopback:connector:mongodb all +0ms Form { where: { status: { exists: false } } }
  loopback:connector:mongodb MongoDB: model=Form command=find +0ms [ { status: { '$exists': false } }, [Function] ]
```

as it should be.

I'm using  "loopback-connector-mongodb": "^1.13.2".

how can i work around this issue?

Thanks!

**Comment by Amir-61** [comment] 2016-01-11 21:47
@noamtz,

I have tried the following syntax and it works;

```
{
  where: {
    myProp: {
      $exists: true
    }
  }
}
```

 could you please create a repo uisng our [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox) to reproduce the issue?

Thanks

**Comment by Amir-61** [comment] 2016-01-22 02:44
I'm closing this ticket since the given solution works. Please feel free to open a ticket if the problem persists.

Thanks a lot!

**Closed** 2016-01-22 02:44 UTC
Labels: triage, waiting

**Comment by adanmuguirofoo** [comment] 2016-08-19 00:27
In my case this operator isn't working, the query always returns 0 results when it should be all the documents in that collection.

I tried $exists, exists and "exists" with the same result, and I'm not using any other condition in my query.

`Model.find({ where: { notExistingProperty: { $exists: false } } }, function(err, results) { });`

Am I missing something? My connector version is 1.13.3.

Thanks,

**Comment by jordanberry** [comment] 2017-04-20 23:20
I was experiencing the same thing and realized I needed to set "allowExtendedOperators": true, for my MongoDB Datasource.

**Comment by snowyu** [comment] 2017-05-09 05:42
It can not work if the field is the string type. the number type is ok

**Comment by israelglar** [comment] 2018-02-07 13:36
@jordanberry solution worked for me.
Added "allowExtendedOperators": true to mongoDB datasource and used:
`{ where: { notExistingProperty: { exists: false } } }`
