### ISSUE TITLE
How I can run a groupby query, a find distinct too.

### ISSUE THREAD

**Issue by Rikhart** [strongloop/loopback-connector-mongodb#39] opened 2014-06-14 04:39 UTC
which is the properly way to run queries like: GROUP BY , or find DISTINCT documents based on a key in a document's collection through Mongodb connector, also mongodb has $agregation and $mapReduce methods, please help me with this. Thank for answers.

**Comment by raymondfeng** [comment] 2015-02-08 19:03
Duplicate of https://github.com/strongloop/loopback-connector-mongodb/issues/74

**Closed by raymondfeng** 2015-02-08 19:03 UTC
