### ISSUE TITLE
updateAttributes() returns either old or updated instance

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-connector-mongodb#157] opened 2015-07-03 17:45 UTC
Based on the [documentation](http://docs.strongloop.com/display/LB/PersistedModel+class#persistedmodel-prototype-updateattributes), `updateAttributes()` is supposed to return updated instance. However, behavior is not completely consistent.
Updated instance is returned here:
- `updateAttributes({description: 'v1', version: 1}, function(err, updated) {...})`

This will return old instance:
- `updateAttributes({'$set': {description: 'v1', version: 1}}, function(err, old) {...})`

Complete example: https://github.com/voitau/loopback-examples/blob/master/mongo-connector/test/petition.test.js#L44-L51

**Comment by satyadeepk** [comment] 2015-08-16 20:19
+1
I am seeing this with `$inc` operation too
`user.updateAttributes({"$inc": {balance: 100}});`

**Comment by zanemcca** [comment] 2015-08-28 16:38
It is probably related to the "new" option on mongoDBs findAndModify function.
You can see the documentation [here](http://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/).

**Comment by raymondfeng** [comment] 2015-08-28 22:44
We should make it explicit via the `options` arg. But not all DBs support it.

**Comment by mrbatista** [comment] 2016-06-14 23:11
@raymondfeng Is there any reason why data returned by callback method `updateAttributes` is not set?
I had a look to the code and the method [updateAttributes](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L1000-L1002) implemented in connector does not return updated data (missed option `{new: true}` in findAndModify as @zanemcca said), also in module **loopback-datasource-juggler** `updateAttributes` callback has only `err` attribute (see [this](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2907)) and data is set by instance method `setAttributes` (see [this](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2885))

**Comment by ssh24** [comment] 2017-06-20 13:43
This is not a bug anymore. I can reproduce `updateAttributes` returning only the updated instance.

Here is a sample code snippet:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }, 
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mongoDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo',
            age: 1
        }, {
            name: 'Bar',
            age: 2
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            Employee.find(function(err, result) {
                if (err) throw err;
                console.log('\nFound instance before update: ' + util.inspect(result));
                
                var employeeInstance = new Employee(result[0]);
                var newData = _.cloneDeep(result[0]);
                newData.name = 'Foo-updated';
                console.log('\nData to be updated: %j', newData);

                employeeInstance.updateAttributes(newData, {validate: false},function(err, result) {
                    if (err) throw err;
                    console.log('\nUpdateAttribute on instance 1: %j', result);

                    Employee.find(function(err, result) {
                        if (err) throw err;
                        console.log('\nFound instance after update: ' + util.inspect(result));
                    });
                });
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:mongodb-157 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { name: 'Foo', age: 1, id: 5948d308ba4fe817a6c4704f },
  { name: 'Bar', age: 2, id: 5948d308ba4fe817a6c47050 } ]

Found instance before update: [ { name: 'Foo', age: 1, id: 5948d308ba4fe817a6c4704f },
  { name: 'Bar', age: 2, id: 5948d308ba4fe817a6c47050 } ]

Data to be updated: {"name":"Foo-updated","age":1,"id":"5948d308ba4fe817a6c4704f"}

UpdateAttribute on instance 1: {"name":"Foo-updated","age":1,"id":"5948d308ba4fe817a6c4704f"}

Found instance after update: [ { name: 'Foo-updated', age: 1, id: 5948d308ba4fe817a6c4704f },
  { name: 'Bar', age: 2, id: 5948d308ba4fe817a6c47050 } ]
```

Closing this issue as it does not exist anymore. Feel free to reopen if needed.

**Closed by ssh24** 2017-06-20 13:43 UTC
Labels: apex

**Comment by chi-tran** [comment] 2019-03-21 08:31
This should not be closed. The $inc returns the old data set. The example only updates an attribute and that works. the $inc does not.
