### ISSUE TITLE
Support for Timestamps Model option 

### ISSUE THREAD

**Issue by FMGordillo** [strongloop/loopback-connector-mongodb#603] opened 2020-11-16 14:14 UTC
## Suggestion

A similar feature to [the mongoose one](https://mongoosejs.com/docs/guide.html#timestamps)

## Use Cases

Avoid manual manipulation of `createdAt` and `updatedAt`

## Examples

```
@model({timestamps: true})
export class Category extends Entity {
// ...
}
```

**Comment by dhmlau** [comment] 2020-11-19 02:37
@raymondfeng @bajtos, do you think this would be better to be implemented as an extension? Thanks.

**Comment by bajtos** [comment] 2020-11-26 15:34
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/1857: _Support auto-updated model properties "createdAt" and "updateAt"_

**Closed by bajtos** 2020-11-26 15:34 UTC
Labels: feature
