### ISSUE TITLE
PrincipleId stored as string in Rolemapping model

### ISSUE THREAD

**Issue by paulJordaan** [strongloop/loopback-connector-mongodb#128] opened 2015-04-22 10:20 UTC
When assigning a role to a user as per the ACL example the principleId field in the Rolemapping model is stored as a string in mongodb. This causes all of the role related functionality to break. When manually changing the principleId to the objectId type it fixes the problem. How can I fix this via code?
```
createdRole.principals.create({
	principalType: RoleMapping.USER,
	principalId: createdUser.id
}, function(err, rolePrincipal) {```

**Comment by nagey** [comment] 2015-05-21 19:15
this is causing problems for me as well. I'd like to avoid manually casting the id to an ObjectID (to maintain datasource portability), but don't see how that is presently possible.

**Comment by erg0dic** [comment] 2016-01-19 17:41
+1, affects me as well

**Comment by alFReD-NSH** [comment] 2016-02-03 17:28
There's two ways, to fix this.

- Make sure when inserting roleMappings, the principalId is ObjectId. Right now there are multiple places in loopback's code that will convert the principalId to string, and this seems to me it is by design, so I guess this is not possible.
- On queries make sure when principalId is not converted to ObjectId. This is fixed in #67, but not merged, due to unresolved compatibility issues and now it's outdated.

**Comment by alFReD-NSH** [comment] 2016-02-06 13:56
Actually it seems like we can set the principalId type to ObjectId and it works(for me at least):

```
      RoleMapping.defineProperty('principalId', {
        type: function(string) {
          return RoleMapping.getDataSource().ObjectID(string);
        }
      });
```

It uses the [`ObjectID` defined by the mongodb connector](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L15-L34) which will handle the cases where the input cannot be converted to ObjectID.

**Comment by jannyHou** [comment] 2016-04-07 19:51
Thank you @alFReD-NSH 
Same issue report in loopback:
https://github.com/strongloop/loopback/issues/1441
Let's keep discussion in that issue.
Thanks for understanding:)

Also post another workaround here just in case someone google and see this issue:
https://github.com/strongloop/loopback/issues/1441#issuecomment-179802633

**Closed by jannyHou** 2016-04-07 19:51 UTC
Labels: triage

**Comment by camcamd** [comment] 2018-06-25 17:52
Correct answer was given by ebarault on https://github.com/strongloop/loopback/issues/3268
