### ISSUE TITLE
Release version 1.17 throws type errors 

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback-connector-mongodb#296] opened 2016-10-18 11:21 UTC
Release version 1.17 is throwing DB type errors.

Using Loopback version 2.29
juggler version 2.46.1
mongodb 3.0.7

Downgrading to version: 1.15.2 resolves the issue.

Full log output:

```
2016-10-18T10:34:30.349669365Z 2016-10-18-10:34:30 1|start    | TypeError: Argument must be a string
2016-10-18T10:34:30.349914461Z 2016-10-18-10:34:30 1|start    |     at TypeError (native)
2016-10-18T10:34:30.350120373Z 2016-10-18-10:34:30 1|start    |     at Buffer.write (buffer.js:575:21)
2016-10-18T10:34:30.350369775Z 2016-10-18-10:34:30 1|start    |     at serializeObjectId (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:242:10)
2016-10-18T10:34:30.350597423Z 2016-10-18-10:34:30 1|start    |     at serializeInto (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:545:17)
2016-10-18T10:34:30.350894807Z 2016-10-18-10:34:30 1|start    |     at serializeObject (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
2016-10-18T10:34:30.351142508Z 2016-10-18-10:34:30 1|start    |     at serializeInto (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
2016-10-18T10:34:30.351351455Z 2016-10-18-10:34:30 1|start    |     at serializeObject (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
2016-10-18T10:34:30.351607717Z 2016-10-18-10:34:30 1|start    |     at serializeInto (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
2016-10-18T10:34:30.351865272Z 2016-10-18-10:34:30 1|start    |     at serializeObject (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:280:18)
2016-10-18T10:34:30.352122599Z 2016-10-18-10:34:30 1|start    |     at serializeInto (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:705:17)
2016-10-18T10:34:30.352353600Z 2016-10-18-10:34:30 1|start    |     at [object Object].serialize (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:47:27)
2016-10-18T10:34:30.352665336Z 2016-10-18-10:34:30 1|start    |     at [object Object].Query.toBin (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:146:25)
2016-10-18T10:34:30.353127833Z 2016-10-18-10:34:30 1|start    |     at [object Object].Cursor._find (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:263:30)
2016-10-18T10:34:30.353289964Z 2016-10-18-10:34:30 1|start    |     at nextFunction (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:576:10)
2016-10-18T10:34:30.353532900Z 2016-10-18-10:34:30 1|start    |     at [object Object].Cursor.next [as _next] (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:693:3)
2016-10-18T10:34:30.353774841Z 2016-10-18-10:34:30 1|start    |     at fetchDocs (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:835:10)
2016-10-18T10:34:30.354012190Z 2016-10-18-10:34:30 1|start    |     at toArray (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:862:3)
2016-10-18T10:34:30.354264772Z 2016-10-18-10:34:30 1|start    |     at [object Object].Cursor.toArray (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:815:44)
2016-10-18T10:34:30.354497486Z 2016-10-18-10:34:30 1|start    |     at processResponse (/src/node_modules/loopback-connector-mongodb/lib/mongodb.js:874:12)
2016-10-18T10:34:30.354771347Z 2016-10-18-10:34:30 1|start    |     at /src/node_modules/loopback-datasource-juggler/lib/observer.js:171:22
2016-10-18T10:34:30.355011023Z 2016-10-18-10:34:30 1|start    |     at doNotify (/src/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
2016-10-18T10:34:30.355253794Z 2016-10-18-10:34:30 1|start    |     at MongoDB.ObserverMixin._notifyBaseObservers (/src/node_modules/loopback-datasource-juggler/lib/observer.js:121:5)
2016-10-18T10:34:30.355493211Z 2016-10-18-10:34:30 1|start    |     at MongoDB.ObserverMixin.notifyObserversOf (/src/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
2016-10-18T10:34:30.355713229Z 2016-10-18-10:34:30 1|start    |     at cbForWork (/src/node_modules/loopback-datasource-juggler/lib/observer.js:161:14)
2016-10-18T10:34:30.355942300Z 2016-10-18-10:34:30 1|start    |     at args.(anonymous function) (/src/node_modules/loopback-connector-mongodb/lib/mongodb.js:276:7)
2016-10-18T10:34:30.356164773Z 2016-10-18-10:34:30 1|start    |     at handleCallback (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:96:12)
2016-10-18T10:34:30.356630240Z 2016-10-18-10:34:30 1|start    |     at [object Object].Collection.find (/src/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/collection.js:354:44)
2016-10-18T10:34:30.356875290Z 2016-10-18-10:34:30 1|start    |     at /src/node_modules/loopback-connector-mongodb/lib/mongodb.js:279:32
2016-10-18T10:34:30.357157059Z 2016-10-18-10:34:30 1|start    |     at /src/node_modules/loopback-datasource-juggler/lib/observer.js:180:9
2016-10-18T10:34:30.357385260Z 2016-10-18-10:34:30 1|start    |     at doNotify (/src/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
2016-10-18T10:34:30.357617047Z 2016-10-18-10:34:30 1|start    |     at MongoDB.ObserverMixin._notifyBaseObservers (/src/node_modules/loopback-datasource-juggler/lib/observer.js:121:5)
2016-10-18T10:34:30.357849931Z 2016-10-18-10:34:30 1|start    |     at MongoDB.ObserverMixin.notifyObserversOf (/src/node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
2016-10-18T10:34:30.358083052Z 2016-10-18-10:34:30 1|start    |     at MongoDB.ObserverMixin.notifyObserversAround (/src/node_modules/loopback-datasource-juggler/lib/observer.js:149:15)
```

**Comment by gvillenave** [comment] 2016-10-19 09:40
I'm seeing the same issue (same client versions, mongodb 3.2.7)

**Comment by jannyHou** [comment] 2016-10-19 20:37
@jamesjjk @gvillenave I run `npm test` on my local with the latest version, but didn't see any error.
Can you elaborate more about how do you get the error?

my local result of `npm test`:
```
  969 passing (26s)
  66 pending
```

**Comment by jamesjjk** [comment] 2016-10-20 09:42
@jannyHou Hi Janny we have taken out this version of our environments, we needed a quick fix. But it could be related to atomic writes, or extended operator usage, just looking at your tests. We also use where so required the mongodb client directly - which is in your documentation too.
```
'allowExtendedOperators': true,
'enableOptimisedfindOrCreate': true, 
```

**Comment by Jeff-Lewis** [comment] 2016-11-18 05:00
FYI - Getting same error with 1.17.0. Reverted to 1.15.2 works fine again.
Node: 4.6.2
juggler: 2.53.0
loopback: 2.36.0
(node) mongodb:  2.2.11
mongodb: 3.0.7

Is it a coincidence that both @jamesjjk and I are running exactly mongodb 3.0.7?

**Comment by jamesjjk** [comment] 2016-11-18 10:11
@Jeff-Lewis Same problem with mongo 3.2 +

**Comment by jannyHou** [comment] 2016-11-18 15:12
@jamesjjk @Jeff-Lewis can you explain more about which endpoint or function you call that getting this error? 
And is it also related to some config variables like
```
'allowExtendedOperators': true,
'enableOptimisedfindOrCreate': true, 
```
If you set them as false do you still run into the problem?

**Comment by Jeff-Lewis** [comment] 2016-11-18 16:59
Is 1.17.0 compatible with juggler 2.28?  npm tests pass with juggler 3, but fail heavily for juggler 2.28.

**Comment by jannyHou** [comment] 2016-11-18 22:22
@Jeff-Lewis 1.17.0 is released with `devDependency` 3.x so I would suggest upgrade your juggler to 3.x version.

And we do have a branch compatible with juggler 2.28 called `loopback-2.x`: https://github.com/strongloop/loopback-connector-mongodb/tree/loopback-2.x

I run test cases on that branch still all pass....

**Comment by jannyHou** [comment] 2016-11-18 22:49
I open an issue to solve the compatibility problem: https://github.com/strongloop/loopback-connector-mongodb/issues/308

@Jeff-Lewis can you post your result of `npm test` here?
I once got 12 failures but now they disappeared....

**Comment by jannyHou** [comment] 2016-11-21 15:48
@Jeff-Lewis Also please note that the latest juggler 2.x version is 2.53.0, please update your juggler to 2.53.0 and see if that will solve your problem.

**Comment by Jeff-Lewis** [comment] 2016-12-02 16:09
@jannyHou Sry, for not getting back earlier. With Juggler 2.53.0, 956 tests passing, 72 pending. Thank you!

**Comment by jannyHou** [comment] 2016-12-05 19:25
ah great! @Jeff-Lewis Do you still run into same error?

I am still trying to reproduce the error, any update on the steps?

**Comment by jamesjjk** [comment] 2017-01-12 17:34
@Jeff-Lewis Have you resolved this issue?

**Comment by jamesjjk** [comment] 2017-01-13 13:12
@jannyHou @superkhau This is resolved in: You should release v1.18 as package please.

loopback 2.37.0
loopback ds juggler 2.53.1
loopback-connector-mongodb version 1.18.0

**Comment by superkhau** [comment] 2017-01-13 18:06
@jamesjjk @bajtos did the release 3 hours ago, you should see 3.0.0 on npmjs.com: https://www.npmjs.com/package/loopback-connector-mongodb

**Comment by superkhau** [comment] 2017-01-13 18:07
@jamesjjk Please give it a try and we can close this issue after you verify the fix.

**Comment by jamesjjk** [comment] 2017-01-13 18:08
@superkhau Is version 3 compatible with loopback 2 users?

**Comment by superkhau** [comment] 2017-01-13 20:07
@jamesjjk Yes, the connectors should be backwards compat -- of course try in a sandbox env first and let us know if you run into issues so we can get it fixed ASAP (or at least document the breaking changes). See http://loopback.io/doc/en/lb3/3.0-Release-Notes.html for changelogs.

**Comment by bajtos** [comment] 2017-01-16 09:57
I believe the only breaking change in loopback-connector-mongodb@3.0.0 is dropping support for Node versions older than 4 (i.e. 0.10, 0.12 and any io.js releases). The connector should keep working with both LoopBack 2.x and 3.x apps.

**Comment by bajtos** [comment] 2017-01-16 09:59
> > Is version 3 compatible with loopback 2 users?

> I believe the only breaking change in loopback-connector-mongodb@3.0.0 is dropping support for Node versions older than 4 (i.e. 0.10, 0.12 and any io.js releases). The connector should keep working with both LoopBack 2.x and 3.x apps.

@superkhau @crandmck should we perhaps emphasise this fact in the release notes? Or maybe in README of each connector? (E.g. create a table showing which connector version to use with which LoopBack version.)

**Comment by superkhau** [comment] 2017-01-16 16:25
I agree with a central table for all the permutations of connectors vs juggler vs lb versions.

**Comment by dhmlau** [comment] 2017-05-12 13:09
@jamesjjk , is this good to close?  Seems to be the problem has been resolved, and there should be enhancement in the doc for compatibility which is addressed in https://github.com/strongloop/loopback-datasource-juggler/issues/1238.  Thanks.

**Comment by dhmlau** [comment] 2017-05-25 15:41
Closing this, we believe it's been resolved.  
@jamesjjk, if you think there's something we need to address here, feel free to reopen.  Thanks.

**Closed by dhmlau** 2017-05-25 15:41 UTC
Labels: major, triaging
