### ISSUE TITLE
strictObjectIDCoercion 1.17.0 bug

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-connector-mongodb#302] opened 2016-10-30 04:06 UTC
This issue is now resurfaced. [ticket](https://github.com/strongloop/loopback-connector-mongodb/issues/52) that also affected to [this ticket](https://github.com/strongloop/loopback/issues/2907), #255

I get the idea behind doing so is to allow querying by _id, but the problem it's causing is any string of length 12 or 24 will be converted too, even worser if those strings matches ObjectID format, they will be converted to ObjectID type when they should remain String type.

**Comment by jannyHou** [comment] 2016-11-15 15:29
@jjhesk Can you describe the bug a little bit here? You can follow this template: https://github.com/strongloop/loopback/issues/new Thanks.

If it's an existed bug please reopen the old issue and mention me.

**Comment by Jeff-Lewis** [comment] 2017-01-14 17:38
In v1.18.0, @fabien [added a setting](https://github.com/strongloop/loopback-connector-mongodb/pull/254#issuecomment-227006561) `strictObjectIDCoercion` that can be set at the dataSource and/or model config. 

@fabien, Thanks though for cleaning all of this up!

When `"strictObjectIDCoercion": true`, it will only convert the string to an `ObjectID` when the model property is specifically defined as an `ObjectID`.

This bit us as well. It appears in v0.15.2, it would not convert strings to `ObjectIDs` for non `ObjectID` properties. Then in 0.17 it started converting all 12/24 character strings to `ObjectIDs` regardless.

IMHO, v0.18 should have set `strictObjectIDCoercion=true` as the default, but @fabien made 0.18 compatible with 0.17, which was a major breaking change/bug. 

Anyway, the `strictObjectIDCoercion` setting should be added to the release notes and docs.

**Comment by mitsos1os** [comment] 2017-01-16 15:45
I agree with what is already said about the new `strictObjectIDCoercion`. This is really important because it also breaks the default loopback Role system in some cases.

If the `User`, `Role` and `RoleMapping` models are defined to use a Mongo DataSource, which will produce IDs of type `ObjectID` instead of simple numeric ones, as opposed to memory data source, the new functionality will try to search for a RoleMapping with `principalId` of type Object instead of string, so no match will return resulting in an unauthorized error to every access that admin role was granted.

This is happening because the `principalId` property that will hold the userId (which is of string type according to RoleMapping model definition), will be converted to an `ObjectId` because of [this](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L1383) functionality, so a query will be sent to database with principalId as objectId type and will return no match

You can reproduce the issue, by taking loopback example https://github.com/strongloop/loopback-example-access-control and adding loopback-connector-mongodb, creating a datasource configuration and assigning all models to use this datasource in model-config.json Then by trying to login as **Bob** (who is an admin in the example) and trying to view all projects (that is only allowed for admin), will get a 401 Unauthorized error

**Comment by sovattha** [comment] 2017-03-29 14:00
Could it be that adding this code solves the issue by only converting strings to ObjectId if not a foreign key?

mongodb.js:725
``` js
if (self.isObjectIDProperty(model, prop, cond)) {
  if (idName == propName) {
    cond = ObjectID(cond);
  }
}
``` 

For me, it works. Of course, the workaround is to set this new property `strictObjectIDCoercion` to true in the model options:

```json
"options": {
  "validateUpsert": true,
  "strictObjectIDCoercion": true
}
```

**Comment by ssh24** [comment] 2017-06-22 18:57
There was a massive gap on the docs for `strictObjectIDCoercion`. It has been added. Refer to it [here](https://loopback.io/doc/en/lb3/MongoDB-connector.html#strictobjectidcoercion-flag).

Closing this issue. Feel free to reopen if needed.

**Closed by ssh24** 2017-06-22 18:57 UTC
Labels: apex, bug
