### ISSUE TITLE
11.3.1 breaks findbyId in mongo

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-mongodb#208] opened 2015-12-15 23:18 UTC
I have a record with id "5656ff55447fe38d129a5767" 

in 11.3.0 the findById in the explorer works just fine, and returns the record
in 11.3.1 it no longer can find the record

https://strongloop/loopback-connector-mongodb@681da1f

may have introduced this problem

**Comment by raymondfeng** [comment] 2015-12-16 00:06
@jmls @BerkeleyTrue Can you provide a test case?

**Comment by raymondfeng** [comment] 2015-12-16 00:11
I cannot reproduce the problem with newly added tests - https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/id.test.js#L134-L152

**Comment by BerkeleyTrue** [comment] 2015-12-16 00:40
Here is where it fails for us https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/models/promo.js#L40

Here is where the job is created initially
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/services/job.js#L25

**Comment by raymondfeng** [comment] 2015-12-16 00:56
@BerkeleyTrue Your job model has the following id: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/models/job.json#L8-L11

Please note its type is set to `string` and `generated` is NOT set to `true`. In this case, LoopBack thinks its type is string, but the generated `_id` is `ObjectId`. In earlier versions, mongodb connector always coerce `_id` to ObjectId if the string matches the pattern.

**Comment by BerkeleyTrue** [comment] 2015-12-16 00:59
@raymondfeng Yes, but that change was introduced and acceptable as ID's were still stored as ObjectID's. The changes introduced in 1.13.1 break this behavior.

**Comment by jmls** [comment] 2015-12-16 09:21
Breaks it badly, I might add - code and systems that were running just fine started failing with some very odd errors. Turns out that a findbyid() is now not working, despite everything looking fine

Whilst I admit guilt in changing the id datatype with data in the db, I *did* run checks and tests and established that no harm was done, and all of our system tests showed that the change was working just fine.

Several releases later, it stops working. This is not good.

**Comment by BerkeleyTrue** [comment] 2016-01-24 04:45
@raymondfeng Would this change also effect queries? I'm finding the state method updateAll no longer behaves the same as well.

**Comment by BerkeleyTrue** [comment] 2016-01-24 05:26
@raymondfeng Just confirmed that the behavior of buildWhere is still breaking queries with id prop.

This: 
```js
return Job.updateAll({ id: id }, { promoCodeUsed: code });
``` 
No longer works. I'm having to hack together code like this to get it to work:

```js
const ObjectID = Promo.app.dataSources.db.ObjectID;

return Job.updateAll({ _id: new ObjectID(id) }, { promoCodeUsed: code });
```
While this works, I'm afraid of other queries throughout the site might be broken as well and will need to revert production back to pre 1.13.1.

Any reason that commit is not reverted and pushed on a major release? 

I hope you understand my frustration as this is the third break I've found from one commit.

**Comment by raymondfeng** [comment] 2016-01-24 05:31
@BerkeleyTrue Sorry for the breaks. Would you please contribute your test cases so that we can make sure there is no regression as we change the code?

**Comment by ssh24** [comment] 2017-06-21 20:34
This is not an issue anymore. `findById` works as expected for both user specified id types and the default ObjectID type on the current version of mongodb connector.

Here is an example code snippet:

**model-definition.json**

- Car
```json
{
  "name": "Car",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "make": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "year": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

- Employee
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "required": true
    },
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mongoDs;
    var Employee = app.models.Employee;
    var Car = app.models.Car;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            id: 1,
            name: 'Foo'
        }, {
            id: 2,
            name: 'Bar'
        }, {
            id: 3,
            name: 'Baz'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated employee instance: ' + util.inspect(result));

            Car.create([{
                make: 'Toyota',
                model: 'Corolla',
                year: 2006
            }, {
                make: 'Honda',
                model: 'Civic',
                year: 2007
            }, {
                make: 'Mercedes Benz',
                model: 'E300',
                year: 2015
            }], function(err, result) {
                if (err) throw err;
                console.log('\nCreated car instance: ' + util.inspect(result));

                var id1 = result[0].id;

                Employee.findById(1, function(err, result) {
                    if (err) throw err;
                    console.log('\nFound employee instance by id: ' + util.inspect(result));

                    Car.findById(id1, function(err, result) {
                        if (err) throw err;
                        console.log('\nFound car instance by id: ' + util.inspect(result));
                    });
                });
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:mongodb-208 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created employee instance: [ { id: 1, name: 'Foo' },
  { id: 2, name: 'Bar' },
  { id: 3, name: 'Baz' } ]

Created car instance: [ { make: 'Toyota',
    model: 'Corolla',
    year: 2006,
    id: 594ad777cc93ceeaba39b5a5 },
  { make: 'Honda',
    model: 'Civic',
    year: 2007,
    id: 594ad777cc93ceeaba39b5a6 },
  { make: 'Mercedes Benz',
    model: 'E300',
    year: 2015,
    id: 594ad777cc93ceeaba39b5a7 } ]

Found employee instance by id: { name: 'Foo', id: 1 }

Found car instance by id: { make: 'Toyota',
  model: 'Corolla',
  year: 2006,
  id: 594ad777cc93ceeaba39b5a5 }
```

Closing this issue as resolved. Feel free to reopen if needed.

**Closed by ssh24** 2017-06-21 20:34 UTC
Labels: apex, bug, major, needs-priority
