### ISSUE TITLE
[BUG] 1.17 vs 1.18 resolving static roles

### ISSUE THREAD

**Issue by pierreclr** [strongloop/loopback-connector-mongodb#327] opened 2017-01-16 15:16 UTC
Hi,

I just encounter a bug upgrading to v1.18. The new way to cast 24hex string to ObjectID seems to conflict the way to resolve role.

Here is the diff between the two versions 
https://github.com/strongloop/loopback-connector-mongodb/compare/8a61bfe...a2f567a

Indeed, in the roleMapping's collection, principalId is persisted as a string. But when enabling the debug mode on v1.18 I'll se this as the incoming request : 
```
loopback:connector:mongodb all +1ms RoleMapping { where:
   { roleId: 587cde8c9d6ec4f58918b86a,
     principalType: 'USER',
     principalId: '587ce0f5e5fa1bff2e855992' },
  limit: 1,
  offset: 0,
  skip: 0 }
```
Which is transform to this mongo request
``` 
 loopback:connector:mongodb MongoDB: model=RoleMapping command=find +1ms [ { roleId: 587cde8c9d6ec4f58918b86a,
    principalType: 'USER',
    principalId: 587ce0f5e5fa1bff2e855992 }
```

As you can see, we are here trying to find an ObjectID despite the principalType persisted as a string. I also verified that by using version 1.17 is looking for a string ..

Maybe related to [this commit](https://github.com/strongloop/loopback-connector-mongodb/commit/0038a29ae0b6c0064a2cf55ac5601bff3836ead1)

**Comment by fabien** [comment] 2017-01-16 15:25
Did you check the new `strictObjectIDCoercion` setting? You might need this here.

**Comment by pierreclr** [comment] 2017-01-16 15:39
@fabien Yes I notice that looking at the code but since the RoleMapping model is a loopback built-in model that I didn't override I didn't consider that setting.

However I imagine that we need to set this setting by default in `loopback/common/models/roleMapping.json` ? But wouldn't be conflictual with loopback running in production ? In fact that's my case and it will imply a mongo migration script ...

**Comment by pierreclr** [comment] 2017-01-18 09:33
Not that this issue imply every static role resolving not working

**Comment by toancong** [comment] 2017-01-21 04:40
You guy changed this api and my production was out because of unable detect role. The change is break api and it should in 3.0 instead 1.18.

**Comment by fabien** [comment] 2017-01-21 09:33
@pierreclr @toancong I'm sorry if the changes had an impact on your apps. The reason for having a `strictObjectIDCoercion` setting in the first place, was precisely to prevent ambiguity of how Strings and ObjectIDs were being handled.

It was a mess before, because anything that *looked* like an ObjectID, was treated as such. Which caused issues with built-in models that did not properly make this distinction (the reverse of what you're experiencing right now, I assume).

To prevent breaking apis, it was added as a flag. However, as you discovered, most people were unaware of this option, and unfortunately it affected core models of already running apps. For any new app, things would just work as intended, as the models were setup correctly right from the start (and before roles were added).

Like you, I felt (and feel) a lot of frustration at times, whenever something broke or was badly implemented. I tried hard to improve this connector times before, but there's hardly anyone dedicated to it at Strongloop/IBM to take care of it properly.

**Comment by pierreclr** [comment] 2017-01-21 12:40
So @fabien do you think you can suggest to loopback team these things to avoid API breaks ?
- Fixing the version of connectors / dependencies in `package.json` OR/AND
- Duplicating loopack's test with all connectors instead of only `in memory db` as test datasource to avoid dependencies related breaks ?

**Comment by lygstate** [comment] 2017-02-20 10:24
I also face this prolbem on mangodb.

**Comment by BuchyOne** [comment] 2017-03-01 02:53
@lygstate  @toancong @pierreclr 

Works without breaking core

https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105

**Comment by b-admike** [comment] 2017-04-24 18:14
hi @pierreclr @fabien this is pretty much the same issue as https://github.com/strongloop/loopback-connector-mongodb/issues/363 and https://github.com/strongloop/loopback-connector-mongodb/pull/370 aims to fix it. Can you pitch in the PR to see if that addresses the root cause? It seems like we want to move towards https://github.com/strongloop/loopback-connector-mongodb/issues/328 as a permanent fix.

**Comment by b-admike** [comment] 2017-04-26 15:06
@pierreclr @toancong can you please see if this is fixed by setting `<modelName>.settings.strictObjectIDCoercion = true` (for e.g. if you want it on the `RoleMapping` model, it'd be `RoleMapping.settings.strictObjectIDCoercion = true` in your boot script?

**Comment by b-admike** [comment] 2017-05-03 14:41
I am going to close this issue because of https://github.com/strongloop/loopback-connector-mongodb/issues/363#issuecomment-297437024. If anyone objects, we can re-open it again and investigate further.

**Closed** 2017-05-03 14:42 UTC
Labels: bug
