### ISSUE TITLE
Loopback Issue with Update Operation - Data Type not stored correctly in Mongo DB

### ISSUE THREAD

**Issue by SandeepVanama** [strongloop/loopback-connector-mongodb#493] opened 2019-01-31 01:45 UTC
I am not able to update the document with correct field data type in Mongo DB using loopback mechanism. I tried with the model JSON file but it is only work for create operation but not for the update operation.

Loopback update operation defining the data types in a model file, is only working for the fields present at root level but not the fields present at Object, Arrary or nested object, nested array level. Fields present at root level alone are updated and saved correctly with the data type defined in model JSON file.

I have attached the sample model JSON file (movies.txt) along with the test output data (movies_sample_output.txt).  I have tested the behavior with the loopback-connector-mongodb@3.9.2 version.

I am new to loopback coding, so can someone help check the issue and implement the fix?  I can perform the testing and confirm the results. 

Please let me know for any more details needed. Thank you in advance..!!

[movies.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2815318/movies.txt)
[Movies_sample_output.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2815319/Movies_sample_output.txt)

**Comment by SandeepVanama** [comment] 2019-02-04 20:33
@dhmlau, could you help with the fix for this issue? We have a project deadline and got stuck with this issue. I am happy to test and confirm the changes upon implementing the fix. Please let me know.

**Comment by dhmlau** [comment] 2019-02-11 21:14
@SandeepVanama, I've created a sample app based on the information you've provided.  https://github.com/dhmlau/loopback-movie-test.

I've tried the following and it seems to be working fine, so if you could let me know how you reproduce the issue, i'd appreciate it.

- after starting the app, in the API Explorer (http://localhost:3000/explorer), i called /POST using the json in `Movies_sample_forCreate.txt` which is a modified version of your txt so that I can successfully make the call.
- then I call `/PATCH` with the only instance I've put, and made changes in the following attributes and they seem to get updated successfully as well:
   - `title` (at the root level)
   - `states` (root level but an array)
   - `tickets` `theatre` (nested properties)


cc @b-admike

**Comment by SandeepVanama** [comment] 2019-02-12 16:50
@dhmlau, Thank you foe checking this.

The main issue here is with the field data type which is not retained as per the model JSON file after the update operation execution. I see the fields that you have tested are string types, not the Decimal, Date and Integer types. Please correct me if I am wrong.

Upon preforming the update operation, the Decimal, Date and Integer type fields are not getting updated with its relevant data types defined in MongoDB (such as NumberDecimal, ISODate and NumberInt etc). Instead they are represented as String data after the update operation. 

I have attached the actual and expected results in "MongoDB_Update_Operation _Loopback-connector-mongodb_3_9_2.docx".  Can you please test the same scenario with Decimal, Date and Integer type fields? Please let me know for any more details needed.

Please check and let me know for any further details needed.

**Comment by SandeepVanama** [comment] 2019-02-12 16:54
Actual results vs Expected results Document uploaded.

[MongoDB_Update_Operation _Loopback-connector-mongodb_3_9_2.docx](https://github.com/strongloop/loopback-connector-mongodb/files/2856754/MongoDB_Update_Operation._Loopback-connector-mongodb_3_9_2.docx)

**Comment by b-admike** [comment] 2019-02-12 19:57
Thank you for the updates @SandeepVanama. Where are you checking the values from to compare actual vs expected? Are you querying what is stored in the mongo database directly or are you checking it in LoopBack's API Explorer?

**Comment by SandeepVanama** [comment] 2019-02-12 21:02
@b-admike  I am checking the results by directly logging into MongoDB database through Studio 3T & Compass tool. Please let me know for anymore details needed.

**Comment by b-admike** [comment] 2019-02-13 18:09
@SandeepVanama I compared two requests (POST and then PATCH by id) using @dhmlau's sample repo, but I don't see any change in the type of the values returned with an update in Compass from the file provided to show actual vs expected results: 

![create_movies_instance](https://user-images.githubusercontent.com/13950637/52733124-edebe780-2f8f-11e9-95ca-241183b1b5b7.png)

I changed some int/decimal values to `1111` and date values to end in `0000`:
![update_movies_instance](https://user-images.githubusercontent.com/13950637/52733128-efb5ab00-2f8f-11e9-8f45-c739c1deea80.png)

Were you using a different endpoint?

**Comment by SandeepVanama** [comment] 2019-02-15 00:09
@b-admike, I am using IBM App Connect Enterprise (ACE) v11.0.0.2 middleware product to integrate with MongoDB.  This product has Loopback Request Node to perform loopback operations. The source code is invisible and embedded with in the product.

The Loopback Request Node takes care of executing the requests by using the connector modules pre-loaded onto ACE. I will upgrade the loopback-connector-mongodb module to version 4.0.0 and test again. 

I am using Studio 3T / Compass software only to verify the results in MongoDB.

Please let me for any clarifications required.

**Comment by b-admike** [comment] 2019-02-19 15:36
@SandeepVanama While I reproduce this issue in a test in mongodb connector, we have landed a recent fix on `loopback-connector` to get nested property definitions properly. Can you please try again using `loopback-connector@4.6.0`? A simple `npm install` if you have the latest (4.0.0) version of mongodb connector should be sufficient. You can check with `npm ls loopback-connector` after.

**Comment by SandeepVanama** [comment] 2019-02-21 16:54
@b-admike, I have tested the scenario with the loopback-connector-mongodb@4.0.0 and loopback-connector@4.6.0 and no change in the behavior. The issue still persists with these connectors modules as well.

Please find below the npm ls loopback-connector and npm ls mongodb command output.

C:\Projects\ace\TESTNODE_ace\node_modules>npm ls loopback-connector
C:\Projects\ace\TESTNODE_ace
`-- loopback-connector-mongodb@4.0.0
  `-- loopback-connector@4.6.0

C:\Projects\ace\TESTNODE_ace\node_modules>npm ls mongodb
C:\Projects\ace\TESTNODE_ace
`-- loopback-connector-mongodb@4.0.0
  `-- mongodb@3.1.13
 
Could you check and let me know if anything else can be tried? Thank you for your support.

**Comment by SandeepVanama** [comment] 2019-02-27 23:49
@b-admike, Please find attached the trace files generated during our testing today with the standalone loopback application shared by @dhmlau. 

Sample JSON File used for testing:
[SampleJSON.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2912684/SampleJSON.txt)

Debug Trace Files:
[CreateOperation_DebugTrace.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2912638/CreateOperation_DebugTrace.txt)
[UpdateOperation_DebugTrace.txt](https://github.com/strongloop/loopback-connector-mongodb/files/2912639/UpdateOperation_DebugTrace.txt)

Issue Discovered:
******************
Create Operation:
--------------------
The Decimal type fields not stored correctly as NumberDecimal when present in nested array level

Update Operation:
--------------------
The Decimal type fields not stored correctly as NumberDecimal when present in any level except at root level.
Issue with Date fields not working as expected. Date fields stored as string value instead of actual Date type value.
Eg:
Actual format stored:  "testDate" : "TIMESTAMP '2019-02-27 16:31:07.813371'", 
Expected format:  "testDate" : ISODate("2019-02-27T16:31:07.813+0000"), 

Please let me know for any more details needed.

**Comment by b-admike** [comment] 2019-04-02 18:43
@SandeepVanama Are you able to test with the code in #501? Please note that it won't fix all of the issues you've observed because it has some dependence on https://github.com/strongloop/loopback-datasource-juggler/pull/1702.

**Comment by b-admike** [comment] 2019-04-12 14:48
This closed automatically because #501 has landed, but will need the fix from https://github.com/strongloop/loopback-datasource-juggler/pull/1702 as well.

**Comment by dhmlau** [comment] 2019-05-24 15:28
Closing as resolved.

**Closed by dhmlau** 2019-05-24 15:28 UTC
Labels: customer, interrupt
